apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  labels:
    app: mongodb
data:
  MONGO_INITDB_ROOT_USERNAME: lukas
  MONGO_INITDB_ROOT_PASSWORD: Cisco0
  MONGO_INITDB_DATABASE: booking
