apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: notification:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8085
          readinessProbe:
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              path: /health/readiness
              port: 8085
          livenessProbe:
            periodSeconds: 60
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              path: /health/liveness
              port: 8085
