version: "3.5"
services:
  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: Cisco0
      POSTGRES_USER: lukas
      POSTGRES_DB: timetable
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
volumes:
  postgres_data: