apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      name: postgresql-pod
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:10
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgresql-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresqldb
      volumes:
        - name: postgresqldb
          persistentVolumeClaim:
            claimName: postgresql-persistent-volume-claim
