/* tslint:disable */
/* eslint-disable */
/**
 * Booking API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: lukas.schoerghuber@posteo.at
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    BookingDto,
    BookingDtoFromJSON,
    BookingDtoToJSON,
    BookingRequestDto,
    BookingRequestDtoFromJSON,
    BookingRequestDtoToJSON,
} from '../models';

export interface BookRequest {
    bookingRequestDto: BookingRequestDto;
}

export interface FindByIdRequest {
    id: string;
}

/**
 * 
 */
export class BookingApi extends runtime.BaseAPI {

    /**
     */
    async bookRaw(requestParameters: BookRequest): Promise<runtime.ApiResponse<BookingDto>> {
        if (requestParameters.bookingRequestDto === null || requestParameters.bookingRequestDto === undefined) {
            throw new runtime.RequiredError('bookingRequestDto','Required parameter requestParameters.bookingRequestDto was null or undefined when calling book.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/booking`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BookingRequestDtoToJSON(requestParameters.bookingRequestDto),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => BookingDtoFromJSON(jsonValue));
    }

    /**
     */
    async book(requestParameters: BookRequest): Promise<BookingDto> {
        const response = await this.bookRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async findByIdRaw(requestParameters: FindByIdRequest): Promise<runtime.ApiResponse<BookingDto>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findById.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/booking/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => BookingDtoFromJSON(jsonValue));
    }

    /**
     */
    async findById(requestParameters: FindByIdRequest): Promise<BookingDto> {
        const response = await this.findByIdRaw(requestParameters);
        return await response.value();
    }

}
