apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      name: booking-pod
      labels:
        app: booking
    spec:
      containers:
        - name: booking
          image: booking:1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8084
          readinessProbe:
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              path: /actuator/health/readiness
              port: 8084
          livenessProbe:
            periodSeconds: 60
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              path: /actuator/health/liveness
              port: 8084
